# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Placeholder for generated protobuf code
# Run compile_protos.sh to generate this file

"""
This file will be generated by running:
    python -m grpc_tools.protoc -I./protos --python_out=. --grpc_python_out=. ./protos/inference.proto

For development purposes, this is a minimal placeholder.
In production, always run the proto compiler.
"""

# Minimal stub to allow imports
class InferenceRequest:
    pass

class InferenceResponse:
    pass

class BoundingBox:
    pass

class HealthCheckRequest:
    pass

class HealthCheckResponse:
    pass

