# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Placeholder for generated gRPC code
# Run compile_protos.sh to generate this file

"""
This file will be generated by running:
    python -m grpc_tools.protoc -I./protos --python_out=. --grpc_python_out=. ./protos/inference.proto

For development purposes, this is a minimal placeholder.
In production, always run the proto compiler.
"""

# Minimal stub to allow imports
class InferenceServiceServicer:
    def Infer(self, request, context):
        pass
    
    def StreamInfer(self, request_iterator, context):
        pass
    
    def HealthCheck(self, request, context):
        pass

def add_InferenceServiceServicer_to_server(servicer, server):
    pass

